RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: '0.0.2'
ComponentDescription: "This Hello World component defers updates when the battery level is below a threshold."
ComponentPublisher: AUTHOR_NAME
ComponentConfiguration:
  DefaultConfiguration:
    BatteryThreshold: 50
    LinuxBatteryFilePath: "/home/ggc_user/virtual_battery.json"
    # /home/ggc_user/virtual_battery.json example:
    # { "battery_level": 80 } or { "battery_level": 30 }
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      install:
        Script: |
          sudo apt update && \
          sudo apt install -y python3 python3-pip python3-venv && \
          python3 -m venv venv && \
          . venv/bin/activate && \
          python3 -m pip install awsiotsdk
      run: |
        . venv/bin/activate
        python3 -u {artifacts:decompressedPath}/files/battery-check-to-defer-update.py "{configuration:/BatteryThreshold}" "{configuration:/LinuxBatteryFilePath}"
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/battery-check-to-defer-update/0.0.2/files.zip
        Unarchive: ZIP
