RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: '0.2.6'
ComponentDescription: COMPONENT_NAME is a python project that publish with IPC/MQTT.
ComponentPublisher: AUTHOR_NAME
ComponentConfiguration:
  DefaultConfiguration:
    MQTTMessage: "Hello I'm mqtt-pub!"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "mqtt-pub:mqttproxy:1":
          policyDescription: Allows access to publish/subscribe to all topics.
          operations:
            - aws.greengrass#PublishToIoTCore
            - aws.greengrass#SubscribeToIoTCore
          resources:
            - "*"
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      install:
        Script: |
          sudo apt update && \
          sudo apt install -y python3 python3-pip python3-venv && \
          python3 -m venv venv && \
          . venv/bin/activate && \
          python3 -m pip install awsiotsdk
      run: |
        . venv/bin/activate
        echo "@Message: {configuration:/Message}"
        python3 -u {artifacts:decompressedPath}/files/mqtt-pub.py "{configuration:/MQTTMessage}"
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/COMPONENT_NAME/0.2.6/files.zip
        Unarchive: ZIP
  - Platform:
      os: windows
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/COMPONENT_NAME/0.2.6/files.zip
        Unarchive: ZIP
    Lifecycle:
      run: |
        python3 -u {artifacts:decompressedPath}/files/mqtt-pub.py "{configuration:/Message}"
