# AWS IoT Greengrass component recipe reference
# https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html
RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: '0.2.9'
ComponentDescription: COMPONENT_NAME is a python project for stream manager client.
ComponentPublisher:
ComponentConfiguration:
  DefaultConfiguration:
    Message: stream-manager-client
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      install:
        Script: |
          sudo apt update && \
          sudo apt install -y python3 python3-pip python3-venv && \
          python3 -m venv venv && \
          . venv/bin/activate && \
          python3 -m pip install awsiotsdk
          python3 -m pip install stream_manager # Stream Manager Client SDK
      run: |
        . venv/bin/activate
        python3 -u {artifacts:decompressedPath}/files/stream-manager-client.py "{configuration:/Message}"
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/stream-manager-client/0.2.9/files.zip
        Unarchive: ZIP
  - Platform:
      os: windows
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/stream-manager-client/0.2.9/files.zip
        Unarchive: ZIP
    Lifecycle:
      run: |
        python3 -u {artifacts:decompressedPath}/files/stream-manager-client.py "{configuration:/Message}"
