RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: '0.0.0'
ComponentDescription: COMPONENT_NAME is a python project that publish with IPC.
ComponentPublisher: AUTHOR_NAME
ComponentConfiguration:
  DefaultConfiguration:
    Message: COMPONENT_NAME
    Topic: "test/topic"
    accessControl:
      aws.greengrass.ipc.pubsub:
        "COMPONENT_NAME:pubsub:1":
          policyDescription: Allows access to publish and subscribe to specific messages.
          operations:
            - "aws.greengrass#PublishToTopic"
            - "aws.greengrass#SubscribeToTopic"
          resources:
            - "test/topic"
            - "other/topic"
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      install:
        Script: |
          sudo apt update && \
          sudo apt install -y python3 python3-pip python3-venv && \
          python3 -m venv venv && \
          . venv/bin/activate && \
          python3 -m pip install awsiotsdk
      run: |
        . venv/bin/activate && \
        python3 -u {artifacts:decompressedPath}/files/ipc-pub.py "{configuration:/Topic}" "{configuration:/Message}"
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/COMPONENT_NAME/0.0.0/files.zip
        Unarchive: ZIP
