RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: '0.0.0'
ComponentDescription: COMPONENT_NAME is a javascript project that says hello world.
ComponentPublisher: AUTHOR_NAME
ComponentConfiguration:
  DefaultConfiguration:
    Message: hello-world
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/hello-world/0.0.0/files.zip
        Unarchive: ZIP
    Lifecycle:
      run: |
        node {artifacts:decompressedPath}/files/hello-world.js "{configuration:/Message}"
  - Platform:
      os: windows
    Artifacts:
      - URI: s3://S3_BUCKET_NAME/artifacts/hello-world/0.0.0/files.zip
        Unarchive: ZIP
    Lifecycle:
      run: |
        node {artifacts:decompressedPath}/files/hello-world.js "{configuration:/Message}"
